name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check
